# Generated by Django 5.2.1 on 2025-05-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=100)),
                ('comments', models.TextField()),
                ('sentiment', models.CharField(max_length=10)),
                ('polarity', models.FloatField()),
            ],
        ),
    ]
