# Generated by Django 5.2.1 on 2025-05-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_event_remove_feedback_event_name_feedback_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
